# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Experience
    url: experience/
    weight: 11
  - name: Research/Projects
    url: projects/
    weight: 12
#  - name: Updates
#    url: /#news
#    weight: 13
  - name: Blog
    url: plot/
    weight: 20
  - name: Publications
    url: /#papers
    weight: 30
  - name: Courses
    url: teaching/
    weight: 40
